### ISSUE TITLE
arch.lightning has no module named base_imaginet

### ISSUE THREAD

**Issue by Magental** [zzzace2000/robust_cls_model#1]
When I re-implemented with this code, I found the following error :

~~~
Traceback (most recent call last):
  File "train_pl.py", line 18, in <module>
    from arch.lightning.csv_recording import CSVRecordingCallback
  File "/home/{$username}/robust_cls_model/arch/lightning/csv_recording.py", line 12, in <module>
    from .base_imagenet import ImageNetLightningModel
ModuleNotFoundError: No module named 'arch.lightning.base_imagenet'
~~~

I think this branch missed about base_imagenet.py in the directory of "/arch/lightning".  or csv_recording.py seems to contain the problem.

**Comment by zzzace2000** [comment]
Thank you so much! Just fix it.

Sorry when cleaning up I forget to remove all logics related to ImageNet-A since they do not work. Thanks again!
